#include <iostream>
#include <string>
#include <windows.h>
#include <stdlib.h>
#include <conio.h>
#include <vector>
#include <set>
#include <cmath>
#include <utility>
#include <ctime>
#include <fstream>
#include <sstream>
#include <cassert>
#include <stdint.h>
#include <stdio.h>